version: "3.9"
services:
  development:
    image: py-node-dev
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: tail -f /dev/null
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
volumes:
  db-pgdata:
