version: "3.9"
services:
  python:
    image: python:3.9
    volumes:
      - .:/workspace
    working_dir: /workspace
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-pgdata:/var/lib/postgresql/data 
volumes:
  db-pgdata:
