version: "3.9"
services:
  development:
    image: py-node-dev
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: tail -f /dev/null
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=nygc-user
      - POSTGRES_PASSWORD=nygc-sweng-rocks!
      - POSTGRES_DB=interview_db
    volumes:
      - db-pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-pgdata:
