version: "3.9"
services:
  development:
    image: python:3.9
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: tail -f /dev/null
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-pgdata:
